/**
 * The three files that make the hub installable: manifest, icon, service
 * worker.
 *
 * Routes rather than files in `bundled/`, for the same reason
 * `/schema/gamecenter.json` is a route: they travel with the module graph, so
 * the server needs no read permission and a missing build step cannot make
 * them 404. It also keeps `sw.js` out of the bundler's output directory, which
 * is wiped of every `.js` before a build.
 *
 * Installing matters beyond the convenience of an icon: on iOS, Web Push works
 * only inside a home-screen PWA, so "add to home screen" is the first half of
 * "notify me".
 */

import type { Action } from "@remix-run/fetch-router";

import icon from "../../assets/icons/icon.svg" with { type: "text" };
import type { routes } from "../routes.ts";

/**
 * The web app manifest.
 *
 * `display: standalone` so a launched hub has no address bar — the landing
 * page is a cabinet and a URL bar above it reads as a browser looking at a
 * cabinet. `theme_color` is the marquee, which is what the navbar wears.
 *
 * `related_applications` names this manifest so `getInstalledRelatedApps()`
 * can confirm an install on the Android Chrome family; `@kuboon/browser-how-to`
 * asks for that as a second signal.
 */
const MANIFEST = {
  name: "game-center",
  short_name: "game-center",
  description: "ミニゲームの実績が集まるハブ。",
  start_url: "/",
  scope: "/",
  display: "standalone",
  lang: "ja",
  background_color: "#06081a",
  theme_color: "#161a35",
  icons: [
    { src: "/icons/icon.svg", sizes: "any", type: "image/svg+xml" },
    {
      src: "/icons/icon.svg",
      sizes: "any",
      type: "image/svg+xml",
      purpose: "maskable",
    },
  ],
  related_applications: [
    { platform: "webapp", url: "/manifest.webmanifest" },
  ],
};

const MANIFEST_BODY = JSON.stringify(MANIFEST, null, 2);

/**
 * The service worker.
 *
 * **It deliberately caches nothing.** A worker is what makes the browser treat
 * this as installable, and that is all this one is for. Serving pages from a
 * cache would mean a player who installed the hub once could keep seeing a
 * catalog and an achievement list that the server has since changed, and every
 * page here is a view of a database that moves.
 *
 * It does carry the push handler, because a notification can only be shown
 * from a worker — that is the one thing a worker is indispensable for here.
 */
const SERVICE_WORKER =
  `// Generated by server/controllers/pwa.ts — do not edit here.
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

// No fetch handler on purpose: every page is a view of a database that moves,
// so a cache would show a player a catalog the server has already changed.

// The IdP signs and sends; this only shows what arrives. The payload is the
// \`notification\` object from \`POST /rp/notifications\`.
self.addEventListener("push", (event) => {
  let payload = {};
  try {
    payload = event.data ? event.data.json() : {};
  } catch {
    // A push with an unreadable body still has to raise something: browsers
    // revoke push permission from a worker that stays silent.
  }
  const data = payload.notification ?? payload;

  event.waitUntil((async () => {
    await self.registration.showNotification(data.title || "game-center", {
      body: data.body || "",
      icon: "/icons/icon.svg",
      badge: "/icons/icon.svg",
      data: { url: data.url || "/me" },
      tag: data.tag,
    });
    // Omitted means "leave the badge alone", which is how the IdP defines it.
    if (typeof data.badgeCount === "number" && self.navigator.setAppBadge) {
      if (data.badgeCount > 0) {
        await self.navigator.setAppBadge(data.badgeCount);
      } else {
        await self.navigator.clearAppBadge();
      }
    }
  })());
});

// Focus a window the hub already has rather than opening a second one.
self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = new URL(
    event.notification.data?.url ?? "/me",
    self.location.origin,
  );
  event.waitUntil((async () => {
    const windows = await self.clients.matchAll({
      type: "window",
      includeUncontrolled: true,
    });
    for (const client of windows) {
      if (new URL(client.url).origin !== url.origin) continue;
      await client.focus();
      if ("navigate" in client) await client.navigate(url.href);
      return;
    }
    await self.clients.openWindow(url.href);
  })());
});
`;

const cached = (body: string, contentType: string, seconds: number) =>
  new Response(body, {
    headers: {
      "content-type": contentType,
      "cache-control": `public, max-age=${seconds}`,
    },
  });

export const manifestAction = {
  handler() {
    return cached(
      MANIFEST_BODY,
      "application/manifest+json; charset=utf-8",
      3600,
    );
  },
} satisfies Action<typeof routes.webManifest>;

export const iconAction = {
  handler() {
    return cached(icon, "image/svg+xml; charset=utf-8", 86400);
  },
} satisfies Action<typeof routes.appIcon>;

export const serviceWorkerAction = {
  handler() {
    // Short: a worker that outlives a change to itself is one the browser
    // keeps asking the old copy about.
    return cached(SERVICE_WORKER, "text/javascript; charset=utf-8", 0);
  },
} satisfies Action<typeof routes.serviceWorker>;
