/**
 * The three files that make the hub installable: manifest, icon, service
 * worker.
 *
 * Routes rather than files in `bundled/`, for the same reason
 * `/schema/gamecenter.json` is a route: they travel with the module graph, so
 * the server needs no read permission and a missing build step cannot make
 * them 404. It also keeps `sw.js` out of the bundler's output directory, which
 * is wiped of every `.js` before a build.
 *
 * Installing matters beyond the convenience of an icon: on iOS, Web Push works
 * only inside a home-screen PWA, so "add to home screen" is the first half of
 * "notify me".
 */

import type { Action } from "@remix-run/fetch-router";

import icon from "../../assets/icons/icon.svg" with { type: "text" };
import type { routes } from "../routes.ts";

/**
 * The web app manifest.
 *
 * `display: standalone` so a launched hub has no address bar — the landing
 * page is a cabinet and a URL bar above it reads as a browser looking at a
 * cabinet. `theme_color` is the marquee, which is what the navbar wears.
 *
 * `related_applications` names this manifest so `getInstalledRelatedApps()`
 * can confirm an install on the Android Chrome family; `@kuboon/browser-how-to`
 * asks for that as a second signal.
 */
const MANIFEST = {
  name: "game-center",
  short_name: "game-center",
  description: "ミニゲームの実績が集まるハブ。",
  start_url: "/",
  scope: "/",
  display: "standalone",
  lang: "ja",
  background_color: "#06081a",
  theme_color: "#161a35",
  icons: [
    { src: "/icons/icon.svg", sizes: "any", type: "image/svg+xml" },
    {
      src: "/icons/icon.svg",
      sizes: "any",
      type: "image/svg+xml",
      purpose: "maskable",
    },
  ],
  related_applications: [
    { platform: "webapp", url: "/manifest.webmanifest" },
  ],
};

const MANIFEST_BODY = JSON.stringify(MANIFEST, null, 2);

/**
 * The service worker.
 *
 * **It deliberately caches nothing.** A worker is what makes the browser treat
 * this as installable, and that is all this one is for. Serving pages from a
 * cache would mean a player who installed the hub once could keep seeing a
 * catalog and an achievement list that the server has since changed, and every
 * page here is a view of a database that moves.
 *
 * It is also where a push handler will go, since a notification can only be
 * shown from a worker.
 */
const SERVICE_WORKER =
  `// Generated by server/controllers/pwa.ts — do not edit here.
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});
// No fetch handler on purpose: every page is a view of a database that moves,
// so a cache would show a player a catalog the server has already changed.
`;

const cached = (body: string, contentType: string, seconds: number) =>
  new Response(body, {
    headers: {
      "content-type": contentType,
      "cache-control": `public, max-age=${seconds}`,
    },
  });

export const manifestAction = {
  handler() {
    return cached(
      MANIFEST_BODY,
      "application/manifest+json; charset=utf-8",
      3600,
    );
  },
} satisfies Action<typeof routes.webManifest>;

export const iconAction = {
  handler() {
    return cached(icon, "image/svg+xml; charset=utf-8", 86400);
  },
} satisfies Action<typeof routes.appIcon>;

export const serviceWorkerAction = {
  handler() {
    // Short: a worker that outlives a change to itself is one the browser
    // keeps asking the old copy about.
    return cached(SERVICE_WORKER, "text/javascript; charset=utf-8", 0);
  },
} satisfies Action<typeof routes.serviceWorker>;
